<a href="https://colab.research.google.com/github/FrankieN-data/binder-notebooks/blob/main/Data_Tech_Solution_Marketing_Campaign_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Understanding Jupyter Notebooks**

Jupyter Notebooks provide an interactive environment that seamlessly integrates code, explanatory text, and visualizations. This allows data professionals to document their entire workflow in a single, shareable document.

Key benefits include:

*   **Comprehensive Documentation:** The ability to combine code and markdown makes it easy to explain the purpose and logic behind each step of a data process.
*   **Enhanced Collaboration:** Notebooks can be easily shared and executed by others, fostering better communication and collaboration within teams.
*   **Reproducibility:** By capturing the entire workflow, notebooks ensure that analyses and processes can be easily reproduced.
*   **Iterative Development:** The interactive nature of notebooks allows for rapid prototyping, testing, and refinement of data pipelines and architectural designs.

In [ ]:
# Import libraries helping with advanced analytics

import pandas as pd

ðŸ“˜*Notebooks need to be connected to some storage location (local, cloud, or mounted drive) to work with files.*

In [ ]:
# Define parameters for file path, filename, and sheet name
file_path = "/content/sample_data/"
file_name = "data_solution_tech.xlsx"
sheet_name = "Data Tech Solution"

# Construct the full file path
full_file_path = file_path + file_name

Dataset loaded successfully using parameters!

ðŸ“˜*Load the dataset in a dataframe (tabular data structure).*

In [ ]:
try:
    df = pd.read_excel(full_file_path, sheet_name=[sheet_name])
    df_data_tech_solution = df[sheet_name]
    print("Dataset loaded successfully using parameters!")

except FileNotFoundError:
    print("Error: Dataset not found. Please check the file path and filename.")

except KeyError:
    print(f"Error: Sheet '{sheet_name}' not found in the workbook.")

except Exception as e:
    print(f"An error occurred: {e}")

## Illustrate Code and Text Combination

One of the key strengths of notebooks is their ability to seamlessly integrate code and explanatory text. This allows us to document our process step-by-step, making it easy for others (or ourselves in the future!) to understand the logic and reproduce the results.

We can use **Markdown cells** like this one to provide explanations, context, and headings, while **Code cells** contain the actual executable code. This creates a narrative flow that makes your data analysis or architectural design clear and understandable.

In [ ]:
df_data_tech_solution = df["Data Tech Solution"]

# Data Understanding
* Dataframe Shape - returns the number of rows and columns
* Head and Trail - show the number of first / last n rows
* Dataframe info - shows data type, number of rows with values
* Describe - basic statistics of numerical columns

In [ ]:
df_data_tech_solution.shape

(40014, 17)

In [ ]:
df_data_tech_solution.head(5)

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Date,Clicks,Impressions,Engagement_Score,Customer_Segment,Unnamed: 15,Campaign Short Month
0,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,12724,5.55,Miami,2021-04-01 00:00:00,217,1820,7,Health & Wellness,NaN,Apr
1,6,DataTech Solutions,Display,All Ages,15 days,Instagram,0.07,9716,4.36,New York,2021-06-01 00:00:00,100,1643,1,Foodies,NaN,Jun
2,8,DataTech Solutions,Search,Men 18-24,45 days,Google Ads,0.08,13280,5.55,Los Angeles,2021-08-01 00:00:00,624,7854,7,Outdoor Adventurers,NaN,Aug
3,20,DataTech Solutions,Influencer,Men 25-34,15 days,Google Ads,0.09,10258,3.83,Miami,20/01/2021,193,3677,1,Tech Enthusiasts,NaN,Jan
4,21,DataTech Solutions,Search,Women 25-34,15 days,Email,0.04,16580,7.99,New York,21/01/2021,975,1561,3,Outdoor Adventurers,NaN,Jan

In [ ]:
df_data_tech_solution.tail()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Date,Clicks,Impressions,Engagement_Score,Customer_Segment,Unnamed: 15,Campaign Short Month
40009,199997,DataTech Solutions,Influencer,Men 18-24,60 days,YouTube,0.09,6697,6.21,New York,2021-03-12 00:00:00,416,2978,7,Fashionistas,NaN,Mar
40010,199998,DataTech Solutions,Social Media,Men 18-24,30 days,Instagram,0.10,12704,6.56,Houston,2021-04-12 00:00:00,930,6086,4,Foodies,NaN,Apr
40011,199999,DataTech Solutions,Influencer,Women 35-44,15 days,Facebook,0.10,18292,3.11,Chicago,2021-05-12 00:00:00,455,2995,6,Fashionistas,NaN,May
40012,200002,DataTech Solutions,Email,Men 25-34,15 days,Facebook,0.02,8168,4.14,Chicago,2021-08-12 00:00:00,228,3068,7,Foodies,NaN,Aug
40013,200003,DataTech Solutions,Social Media,Men 18-24,45 days,Website,0.05,13397,3.25,New York,2021-09-12 00:00:00,723,9548,3,Tech Enthusiasts,NaN,Sep

In [ ]:
df_data_tech_solution.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40014 entries, 0 to 40013
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Campaign_ID           40014 non-null  int64
 1   Company               40014 non-null  object
 2   Campaign_Type         40014 non-null  object
 3   Target_Audience       40014 non-null  object
 4   Duration              40014 non-null  object
 5   Channel_Used          40014 non-null  object
 6   Conversion_Rate       40014 non-null  float64
 7   Acquisition_Cost      40014 non-null  int64
 8   ROI                   40014 non-null  float64
 9   Location              40014 non-null  object
 10  Date                  40014 non-null  object
 11  Clicks                40014 non-null  int64
 12  Impressions           40014 non-null  int64
 13  Engagement_Score      40014 non-null  int64
 14  Customer_Segment      40014 non-null  object
 15  Unnamed: 15           0 non-null      float64
 16  Campaign Short Month  40014 non-null  object
dtypes: float64(3), int64(5), object(9)
memory usage: 5.2+ MB

In [ ]:
df_data_tech_solution.describe()

,Campaign_ID,Conversion_Rate,Acquisition_Cost,ROI,Clicks,Impressions,Engagement_Score,Unnamed: 15
count,40014.00000,40014.000000,40014.000000,40014.000000,40014.000000,40014.000000,40014.000000,0.0
mean,100074.82841,0.079987,12503.189609,5.005472,550.871345,5504.697106,5.501400,NaN
std,57829.55013,0.040702,4343.288323,1.732884,260.379236,2596.466951,2.871777,NaN
min,4.00000,0.010000,5000.000000,2.000000,100.000000,1000.000000,1.000000,NaN
25%,49836.75000,0.040000,8725.000000,3.510000,324.000000,3273.250000,3.000000,NaN
50%,100377.00000,0.080000,12450.500000,5.000000,552.000000,5503.500000,5.000000,NaN
75%,150085.25000,0.110000,16299.000000,6.520000,776.000000,7747.750000,8.000000,NaN
max,200003.00000,0.150000,20000.000000,8.000000,1000.000000,10000.000000,10.000000,NaN

#### Data Preparation (Data Cleaning)

* Check for missing values
* drop rows with missing values
* Check for Duplicate Rows
* Remove Duplicate Rows
* Rename Column
* Drop irrelvant Colum

In [ ]:
df_data_tech_solution.drop(columns=['Unnamed: 15'], inplace=True)

In [ ]:
df_data_tech_solution.shape

(40014, 16)

In [ ]:
# Check for missing value
df_data_tech_solution.isnull().sum()

Campaign_ID             0
Company                 0
Campaign_Type           0
Target_Audience         0
Duration                0
Channel_Used            0
Conversion_Rate         0
Acquisition_Cost        0
ROI                     0
Location                0
Date                    0
Clicks                  0
Impressions             0
Engagement_Score        0
Customer_Segment        0
Campaign Short Month    0
dtype: int64

In [ ]:
df_data_tech_solution[df_data_tech_solution.isnull().any(axis=1)]
df_data_tech_solution.isnull().sum()

Campaign_ID             0
Company                 0
Campaign_Type           0
Target_Audience         0
Duration                0
Channel_Used            0
Conversion_Rate         0
Acquisition_Cost        0
ROI                     0
Location                0
Date                    0
Clicks                  0
Impressions             0
Engagement_Score        0
Customer_Segment        0
Campaign Short Month    0
dtype: int64

In [ ]:
df_data_tech_solution.dropna(inplace=True)

In [ ]:
# check for duplicate

df_data_tech_solution.duplicated().sum()

0

# Task
Create a notebook that serves as a presentation for a data architect unfamiliar with notebooks, demonstrating the key features and benefits outlined in the provided text.

## Introduce notebooks

### Subtask:
Start with a clear explanation of what notebooks are and their purpose, incorporating the key points from your first slide.

**Reasoning**:
Create a markdown cell at the beginning of the notebook to explain what Jupyter Notebooks are and their benefits for a data architect.

## Demonstrate data import and exploration

### Subtask:
Show how easy it is to import data and perform initial data exploration steps using code cells. This aligns with the "import datasets and experiment with data" point.

**Reasoning**:
Import the pandas library to work with dataframes.